### ISSUE TITLE
TypeError: Cannot read property 'callee' of undefined

### ISSUE THREAD

**Issue by akinjide** [you-dont-need/You-Dont-Need-Lodash-Underscore#225] opened 2019-10-16 14:50 UTC
VERSION: `^6.7.1`
NODE VERSION: `v8.9.3 (npm v5.5.1)`

Throws error:
```bash
TypeError: Cannot read property 'callee' of undefined
Occurred while linting lib/errors.js:5
    at CallExpression (/node_modules/eslint-plugin-you-dont-need-lodash-underscore/lib/rules/all.js:28:101)
    at listeners.(anonymous function).forEach.listener (/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at nodeQueue.forEach.traversalInfo (/node_modules/eslint/lib/linter/linter.js:935:32)
    at Array.forEach (<anonymous>)
```

in `lib/error.js`

```javascript
constructor(statusCode, message, body) {
    super(message);     // line 5
}
```

It seems like an issue with the recent version of `eslint-plugin-you-dont-need-lodash-underscore`. Using an older version, 6.7.0 works.

**Comment by cjtaylor1990** [comment] 2019-10-16 15:01
Likely a similar issue to what was just fixed in #221.

If you would want to try to fix it, in lib/rules/all.js, try changing:
`
const objectName = callee.name || (callee.object && callee.object.name) || (callee.object.callee && callee.object.callee.name);
`
to

`
const objectName = callee.name || (callee.object && callee.object.name) || (callee.object && callee.object.callee && callee.object.callee.name);
`

I'm sure this will be fixed in the next version. Obviously, you can always just use the previous version as you said.

**Comment by akinjide** [comment] 2019-10-16 15:14
Thank you. Do you have an ETA for the next version?

**Comment by cht8687** [comment] 2019-10-17 05:47
I can do a patch release for this once it's been fixed. @cjtaylor1990

**Comment by cjtaylor1990** [comment] 2019-10-17 05:51
@cht8687 This is fixed by #221, even though the cause of the error was different. I could add a test to make sure the linter can handle sub-classes like this though, just to be thorough.

**Comment by cht8687** [comment] 2019-10-17 05:58
sorry, I misunderstood the question. all good. it's released.

https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/releases/tag/v6.7.2

**Comment by cjtaylor1990** [comment] 2019-10-17 06:00
@akinjide There you go. A new version has been released. Let us know if that clears everything up.

**Closed** 2019-10-17 09:00 UTC
